[package]
name = "cartero"
version = "0.2.3"
edition = "2021"

[features]
default = ["csd"]
csd = []
app_updater = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adw = { version = "0.7.1", package = "libadwaita", features = ["v1_5"] }
base64 = "0.22.1"
formatx = "0.2.3"
formdata = "0.13.0"
futures-lite = "2.6.0"
gettext-rs = { version = "0.7.2", features = ["gettext-system"] }
glib = { version = "0.20.9", features = ["v2_72"] }
gtk = { package = "gtk4", version = "0.9.6", features = ["v4_12"] }
indexmap = "2.8.0"
isahc = "1.7.2"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["preserve_order"] }
serde_urlencoded = "0.7.1"
sourceview5 = "0.9.1"
srtemplate = { version = "0.3.2", features = [] }
tokio = { version = "1.44.1", features = ["sync"] }
toml = "0.8.20"
url = "2.5.4"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["dwmapi"] }
gdk4-win32 = '0.9.5'

[build-dependencies]
winresource = "0.1.20"
