# Copyright 2024-2025 the Cartero authors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later

[workspace]
members = ["cartero-*"]

[workspace.package]
edition = "2021"
version = "0.3.0"
license = "GPL-3.0-or-later"

[workspace.dependencies]
askama = "0.14.0"
base64 = "0.22.1"
content_disposition = "0.4.0"
formdata = "0.13.0"
futures-lite = "2.6.1"
glib = { version = "0.21.1", features = ["v2_80"] }
gio = { version = "0.21.1", features = ["v2_80"] }
http = "1.3.1"
indexmap = { version = "2.10.0", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
srtemplate = "0.3.3"
serde_urlencoded = "0.7.1"
toml = "0.8.23"
tokio = { version = "1.47.1", features = ["rt", "macros", "sync"] }
url = "2.5.6"

[package]
name = "cartero"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["csd"]
csd = []
app_updater = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adw = { version = "0.8.0", package = "libadwaita", features = ["v1_5"] }
base64.workspace = true
cartero_http = { path = "cartero-http" }
cartero_interop = { path = "cartero-interop" }
cartero_isahc_client = { path = "cartero-isahc-client" }
cartero_code_exporters = { path = "cartero-code-exporters" }
cartero_objects = { path = "cartero-objects" }
cartero_file_format = { path = "cartero-file-format" }
formatx = "0.2.4"
formdata.workspace = true
futures-lite.workspace = true
gettext-rs = { version = "0.7.2", features = ["gettext-system"] }
glib.workspace = true
gtk = { package = "gtk4", version = "0.10.0", features = ["v4_14"] }
indexmap.workspace = true
serde.workspace = true
serde_json = { version = "1.0.143", features = ["preserve_order"] }
serde_urlencoded.workspace = true
sourceview5 = { version = "0.10.0", features = ["v5_12"]}
srtemplate.workspace = true
tokio.workspace = true
toml.workspace = true
url.workspace = true
addr = "0.15.6"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["dwmapi", "winnt", "sysinfoapi"] }
windows-sys = { version = "0.60.2", features = [
    "Wdk",
    "Wdk_System",
    "Wdk_System_SystemServices",
    "Win32_System_SystemInformation",
]}
gdk4-win32 = '0.10.0'

[build-dependencies]
winresource = "0.1.23"

[target.'cfg(target_os = "macos")'.dependencies]
gdk4-macos = { version = '0.10.0', features = ["cocoa"] }
objc2 = "0.6.2"
objc2-foundation = "0.3.1"
objc2-app-kit = "0.3.1"
objc2-core-graphics = "0.3.1"
objc2-core-foundation = "0.3.1"