option(
  'profile',
  type: 'combo',
  choices: [
    'default',
    'development'
  ],
  value: 'default',
  description: 'The build profile for Cartero. One of "default" or "development".'
)

option(
  'decorations',
  type: 'combo',
  choices: [
    'csd',
    'no-csd',
  ],
  value: 'csd',
  description: 'Whether to use client side decorations. One of "csd" or "no-csd"'
)

# Package maintainers: this option is designed for the AppImage, Windows and macOS
# artifacts hosted at the project website. You might want to keep this feature
# disabled if the package manager or repository already manages updates on behalf
# of the user (true for Flathub, Snapcraft, AUR, and many others).
option(
  'app-updater',
  type: 'feature',
  value: 'disabled',
  description: 'Whether to enable in-app software update checker',
)

# When running the install target, will also create an AppImage.
option(
  'appimage',
  type: 'feature',
  value: 'disabled',
  description: 'Whether to create an AppImage when installing',
)
