POST https://staging.shop.example.com/send?to=O%27Donnell
Content-Type: multipart/form-data; boundary=UE9TVCBodHRwczovL3N0YWdpbmcuc2hvcC5leGFtcGxlLmNvbS9zZW5kP3RvPU8lMjdEb25uZWxs

--UE9TVCBodHRwczovL3N0YWdpbmcuc2hvcC5leGFtcGxlLmNvbS9zZW5kP3RvPU8lMjdEb25uZWxs
Content-Disposition: form-data; name="normal"

good "morning" world
--UE9TVCBodHRwczovL3N0YWdpbmcuc2hvcC5leGFtcGxlLmNvbS9zZW5kP3RvPU8lMjdEb25uZWxs
Content-Disposition: form-data; name="single"

good 'afternoon' world
--UE9TVCBodHRwczovL3N0YWdpbmcuc2hvcC5leGFtcGxlLmNvbS9zZW5kP3RvPU8lMjdEb25uZWxs--
