<p>Changed:</p>
<ul>
<li>Pressing the Tab or the Shift-Tab keys in a request table (parameters, variables...) will now skip the row itself and focus instead an actual component like the checkbox or the dropdown menu.</li>
<li>MacOS: on systems with a dual graphics card setup, Cartero will now run on the integrated rather than the discrete one. (This is good, it will save a lot of battery.)</li>
<li>Translation updates: Spanish, French, Galician, Brazilian Portuguese, Russian.</li>
</ul>
<p>Fixed:</p>
<ul>
<li>Fixed accessibility issues: missing labels and tooltips within some window widgets.</li>
<li>Some keyboard shortcuts were not being described by thee Keyboard Shortcuts help dialog.</li>
<li>The dropdown menu for the request method had the wrong appearance when the computer uses a right-to-left layout (such as Arabic or Hebrew).</li>
<li>MacOS: Zoom in, zoom out, zoom reset and search keyboard shortcuts for code views were using the wrong keyboard modifiers.</li>
</ul>
