<p>Added:</p>
<ul>
  <li>Added a color scheme selector for the code views.</li>
  <li>Added application window theming and tinting.</li>
  <li>Added a menu option to duplicate requests.</li>
</ul>
<p>Changed:</p>
<ul>
  <li>The response pane will now render the effective URL of a response.</li>
  <li>It is now possible to reveal the values of .env variables in the endpoint pane.</li>
</ul>
<p>Fixed:</p>
<ul>
  <li>Responses were being treated as binary if they contained the CR (\r) character.</li>
  <li>Disabling TLS validation still failed a request if the certificate didn't have a matching SAN.</li>
  <li>MacOS: the main application window could sometimes stop receiving mouse clicks on macOS 26.</li>
</ul>
<p>Translation Updates:</p>
<ul>
  <li>Basque</li>
  <li>Indonesian</li>
  <li>Portuguese (Brazil)</li>
  <li>Chinese (Simplified)</li>
</ul>
