# Copyright 2024-2025 the Cartero authors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
name: Build
jobs:
  flake:
    strategy:
      matrix:
        platform:
          - runs-on: ubuntu-latest
            name: x86_64
          - runs-on: ubuntu-24.04-arm
            name: aarch64
    runs-on: ${{ matrix.platform.runs-on }}
    name: "Flake ${{ matrix.platform.name }}"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix build
      - run: nix flake check
  flatpak:
    strategy:
      matrix:
        platform:
          - runs-on: ubuntu-latest
            name: x86_64
          - runs-on: ubuntu-24.04-arm
            name: aarch64
      fail-fast: false
    runs-on: ${{ matrix.platform.runs-on }}
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    name: "Flatpak ${{ matrix.platform.name }}"
    steps:
      - uses: actions/checkout@v4
      - name: Generate version code
        id: version-code
        run: |
          echo "CARTERO_NIGHTLY_VERSION=1" >> $GITHUB_ENV
          echo "version=$(build-aux/gen-nightly-version.py --nightly)" >> $GITHUB_OUTPUT
          echo "full-version=$(build-aux/gen-nightly-version.py --nightly)-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: Cartero-${{ steps.version-code.outputs.full-version }}-${{ matrix.platform.name }}.flatpak
          manifest-path: build-aux/es.danirod.Cartero.Devel.json
          cache-key: flatpak-builder-${{ github.sha }}-${{ matrix.platform.name }}
          build-bundle: true
          arch: ${{ matrix.platform.name }}
          upload-artifact: false
      - uses: actions/upload-artifact@v4
        with:
          name: Cartero-${{ steps.version-code.outputs.full-version }}-flatpak-${{ matrix.platform.name }}
          path: Cartero-*.flatpak
  windows:
    strategy:
      matrix:
        platform:
          - runs-on: windows-latest
            name: x64
            msystem: ucrt64
          - runs-on: windows-11-arm
            name: arm64
            msystem: clangarm64
      fail-fast: false
    runs-on: ${{ matrix.platform.runs-on }}
    name: "Windows ${{ matrix.platform.name }}"
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
        pacboy: >-
          blueprint-compiler
          desktop-file-utils
          gcc
          gettext
          gtk4
          gtksourceview5
          jq
          libadwaita
          librsvg
          libxml2
          meson
          pkgconf
          rust
        msystem: ${{ matrix.platform.msystem }}
    - uses: actions/checkout@v4
    - name: Generate version code
      id: version-code
      run: |
        echo "CARTERO_NIGHTLY_VERSION=1" >> $GITHUB_ENV
        echo "version=$(build-aux/gen-nightly-version.py --nightly)" >> $GITHUB_OUTPUT
        echo "full-version=$(build-aux/gen-nightly-version.py --nightly)-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
    - name: Build Windows version
      run: |
        meson setup build -Dprofile=development -Ddecorations=no-csd -Dwin32-bundle=enabled --prefix=\\
        DESTDIR=$PWD/build/cartero-win32 ninja -C build install
    - uses: actions/upload-artifact@v4
      name: Upload Windows version
      with:
        name: cartero-${{ steps.version-code.outputs.full-version }}-windows-${{ matrix.platform.name }}
        path: |
          build/cartero-win32/bin
          build/cartero-win32/lib
          build/cartero-win32/share
  macos:
    strategy:
      matrix:
        platform:
          - runs-on: macos-13
            name: x64
          - runs-on: macos-15
            name: arm64
      fail-fast: false
    name: "macOS ${{ matrix.platform.name }}"
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: brew install meson gtk4 gtksourceview5 desktop-file-utils pygobject3 libadwaita adwaita-icon-theme shared-mime-info create-dmg
    - name: Fix PYTHONPATH for blueprint-compiler
      run: echo "PYTHONPATH=$(brew --prefix)/lib/python3.13/site-packages:$PYTHONPATH" >> $GITHUB_ENV
    - name: Fix GETTEXT_DIR for macOS
      run: echo "GETTEXT_DIR=$(brew --prefix)/opt/gettext" >> $GITHUB_ENV
    - name: Generate version code
      id: version-code
      run: |
        echo "CARTERO_NIGHTLY_VERSION=1" >> $GITHUB_ENV
        echo "version=$(build-aux/gen-nightly-version.py --nightly)" >> $GITHUB_OUTPUT
        echo "full-version=$(build-aux/gen-nightly-version.py --nightly)-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
    - name: Build macOS version
      run: |
        meson setup -Dprofile=development -Dmacos-app=enabled --prefix=/ build
        DESTDIR=$PWD/output ninja -C build install
    - uses: actions/upload-artifact@v4
      name: Upload macOS version
      with:
        name: Cartero-${{ steps.version-code.outputs.full-version }}-macOS-${{ matrix.platform.name }}
        path: output/*
  appimage:
    strategy:
      matrix:
        platform:
          - runs-on: ubuntu-latest
            name: x86_64
          - runs-on: ubuntu-24.04-arm
            name: aarch64
      fail-fast: false
    runs-on: ${{ matrix.platform.runs-on }}
    name: "AppImage ${{ matrix.platform.name }}"
    steps:
    - name: Install dependencies
      run: sudo apt install --no-install-recommends desktop-file-utils gettext libadwaita-1-dev libfuse2 libgtk-4-bin libgtk-4-dev libgtksourceview-5-dev librsvg2-common meson jq
    - uses: actions/checkout@v4
    - name: Generate version code
      id: version-code
      run: |
        echo "CARTERO_NIGHTLY_VERSION=1" >> $GITHUB_ENV
        echo "version=$(build-aux/gen-nightly-version.py --nightly)" >> $GITHUB_OUTPUT
        echo "full-version=$(build-aux/gen-nightly-version.py --nightly)-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
    - name: Build
      run: |
        meson setup build -Dappimage=enabled -Dprofile=development --prefix=/usr
        ninja -C build
        DESTDIR=$PWD/AppDir ninja -C build install
        curl -LO https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-$(uname -m).AppImage
        chmod a+x appimagetool-$(uname -m).AppImage
        VERSION="${{ steps.version-code.outputs.full-version }}" ./appimagetool-$(uname -m).AppImage AppDir
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Cartero-${{ steps.version-code.outputs.full-version }}-appimage-${{ matrix.platform.name }}
        path: Cartero-*.AppImage
