# Copyright 2024-2025 the Cartero authors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
name: Build
jobs:
  flatpak:
    strategy:
      matrix:
        platform:
          - runs-on: ubuntu-latest
            name: x86_64
          - runs-on: ubuntu-24.04-arm
            name: aarch64
      fail-fast: false
    runs-on: ${{ matrix.platform.runs-on }}
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    name: "Flatpak ${{ matrix.platform.name }}"
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: es.danirod.Cartero.Devel.flatpak
          manifest-path: build-aux/es.danirod.Cartero.Devel.json
          cache-key: flatpak-builder-${{ github.sha }}
          build-bundle: true
          arch: ${{ matrix.platform.name }}
  windows:
    strategy:
      matrix:
        platform:
          - runs-on: windows-latest
            name: x64
            msystem: ucrt64
          - runs-on: windows-11-arm
            name: arm64
            msystem: clangarm64
      fail-fast: false
    runs-on: ${{ matrix.platform.runs-on }}
    name: "Windows ${{ matrix.platform.name }}"
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
        pacboy: >-
          blueprint-compiler
          desktop-file-utils
          gcc
          gettext
          gtk4
          gtksourceview5
          libadwaita
          librsvg
          libxml2
          meson
          pkgconf
          rust
        msystem: ${{ matrix.platform.msystem }}
    - uses: actions/checkout@v4
    - name: Build Windows version
      run: |
        meson setup build -Dprofile=development -Dapp-updater=enabled -Ddecorations=no-csd --prefix=\\
        DESTDIR=$PWD/build/cartero-win32 ninja -C build install
    - name: Create Windows installer
      run: |
        "C:\Program Files (x86)\Inno Setup 6\iscc.exe" build/cartero-win32/installer.iss
    - uses: actions/upload-artifact@v4
      name: Upload Windows version
      with:
        name: cartero-${{ github.sha }}-windows-${{ matrix.platform.name }}-portable
        path: |
          build/cartero-win32/bin
          build/cartero-win32/lib
          build/cartero-win32/share
    - uses: actions/upload-artifact@v4
      name: Upload Windows version
      with:
        name: cartero-${{ github.sha }}-windows-${{ matrix.platform.name }}-installer
        path: build/cartero-win32/Output/cartero-*.exe
  macos:
    strategy:
      matrix:
        platform:
          - runs-on: macos-13
            name: x64
          - runs-on: macos-15
            name: arm64
      fail-fast: false
    name: "macOS ${{ matrix.platform.name }}"
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: brew install pkg-config meson gtk4 gtksourceview5 desktop-file-utils pygobject3 libadwaita adwaita-icon-theme shared-mime-info create-dmg && brew link pkgconf
    - name: Fix PYTHONPATH for blueprint-compiler
      run: echo "PYTHONPATH=$(brew --prefix)/lib/python3.13/site-packages:$PYTHONPATH" >> $GITHUB_ENV
    - name: Fix GETTEXT_DIR for macOS
      run: echo "GETTEXT_DIR=$(brew --prefix)/opt/gettext" >> $GITHUB_ENV
    - name: Build macOS version
      run: |
        meson rewrite kwargs set project / version $(build-aux/gen-nightly-version.sh)
        meson setup -Dmacos-dmg=enabled build
        DESTDIR=$PWD/output ninja -C build install
        mv output/Cartero.dmg Cartero-$(build-aux/gen-nightly-version.sh)-macOS-${{ matrix.platform.name }}.dmg
    - uses: actions/upload-artifact@v4
      name: Upload macOS version
      with:
        name: Cartero-${{github.sha }}-macOS-${{ matrix.platform.name }}
        path: output/Cartero*.dmg
  appimage:
    strategy:
      matrix:
        platform:
          - runs-on: ubuntu-latest
            name: x86_64
          - runs-on: ubuntu-24.04-arm
            name: aarch64
      fail-fast: false
    runs-on: ${{ matrix.platform.runs-on }}
    name: "AppImage ${{ matrix.platform.name }}"
    steps:
    - name: Install dependencies
      run: sudo apt install --no-install-recommends desktop-file-utils gettext libadwaita-1-dev libfuse2 libgtk-4-bin libgtk-4-dev libgtksourceview-5-dev librsvg2-common meson
    - uses: actions/checkout@v4
    - name: Build
      run: |
        meson setup build -Dappimage=enabled -Dprofile=development --prefix=/usr
        ninja -C build
        DESTDIR=$PWD/AppDir ninja -C build install
        curl -LO https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-$(uname -m).AppImage
        chmod a+x appimagetool-$(uname -m).AppImage
        ./appimagetool-$(uname -m).AppImage AppDir
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: es.danirod.Cartero.Devel-${{ matrix.platform.name }}.AppImage
        path: Cartero-${{ matrix.platform.name }}.AppImage
