# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: the Cartero authors

name: Nightly release

on:
  push:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    name: Build nightly dist
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      sign: false
      profile: 'nightly'
