# Copyright 2024-2026 the Cartero authors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Nightly release

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  # Automatic deployment is only triggered if there are new changes.
  check-new-commits:
    name: Check if there are new commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: get new commits
        id: check
        run: |
          # Manual workflows are always true even when no commits have been made.
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "new-commits=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          if [ -z "$(git rev-list --after="24 hours" HEAD)" ]; then
            echo "new-commits=false" >> $GITHUB_OUTPUT
          else
            echo "new-commits=true" >> $GITHUB_OUTPUT
          fi
    outputs:
      new-commits: ${{ steps.check.outputs.new-commits }}

  # This is the one that triggers the whole set. Runs on manual or if check-new-commits was true.
  prepare-dist:
    name: Prepare nightly dist
    needs: [check-new-commits]
    if: ${{ needs.check-new-commits.outputs.new-commits == 'true' }}
    runs-on: ubuntu-latest
    env:
      CARTERO_NIGHTLY_VERSION: 1
    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y --no-install-recommends gettext meson libgtk-4-dev libadwaita-1-dev libgtksourceview-5-dev desktop-file-utils xvfb
      - name: Clone code
        uses: actions/checkout@v4
      - name: Generate version code
        id: version-code
        run: echo "version=$(build-aux/gen-version.py --nightly)" >> $GITHUB_OUTPUT
      - name: Setup project
        run: meson setup build
      - name: Build dist
        run: meson dist -C build --no-tests
      - name: Upload dist
        uses: actions/upload-artifact@v6
        id: upload-dist
        with:
          name: cartero-${{ steps.version-code.outputs.version }}.tar.xz
          path: build/meson-dist/*
          compression-level: 0
      - name: Assess version
        run: |
          cd build/meson-dist
          tar -xf cartero-${{ steps.version-code.outputs.version }}.tar.xz
          cd cartero-${{ steps.version-code.outputs.version }}
          cat meson.build
    outputs:
      version: ${{ steps.version-code.outputs.version }}
      root: cartero-${{ steps.version-code.outputs.version }}
      dist: cartero-${{ steps.version-code.outputs.version }}.tar.xz
      artifact-id: ${{ steps.upload-dist.outputs.artifact-id }}

  # This is the one that builds the Flatpak package.
  gnulinux-flatpak:
    needs: [prepare-dist]
    strategy:
      matrix:
        platform:
          - runs-on: ubuntu-latest
            name: x86_64
          - runs-on: ubuntu-24.04-arm
            name: aarch64
      fail-fast: false
    runs-on: ${{ matrix.platform.runs-on }}
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-49
      options: --privileged
    name: "GNU/Linux Flatpak ${{ matrix.platform.name }}"
    steps:
      - name: Fetch dist
        uses: actions/download-artifact@v7
        with:
          artifact-ids: ${{ needs.prepare-dist.outputs.artifact-id }}
      - name: Extract dist
        run: tar -xf ${{ needs.prepare-dist.outputs.dist }}
      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: Cartero-${{ needs.prepare-dist.outputs.version }}-${{ matrix.platform.name }}.flatpak
          manifest-path: ${{ needs.prepare-dist.outputs.root }}/build-aux/es.danirod.Cartero.Devel.json
          cache-key: flatpak-builder-${{ github.sha }}-${{ matrix.platform.name }}
          build-bundle: true
          arch: ${{ matrix.platform.name }}
          upload-artifact: false
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: Cartero-${{ needs.prepare-dist.outputs.version }}-${{ matrix.platform.name }}.flatpak
          path: Cartero-*.flatpak

  # This one builds the AppImage package
  gnulinux-appimage:
    needs: [prepare-dist]
    strategy:
      matrix:
        platform:
          - runs-on: ubuntu-latest
            name: x86_64
          - runs-on: ubuntu-24.04-arm
            name: aarch64
      fail-fast: false
    runs-on: ${{ matrix.platform.runs-on }}
    name: "GNU/Linux AppImage ${{ matrix.platform.name }}"
    steps:
    - name: Fetch dist
      uses: actions/download-artifact@v7
      with:
        artifact-ids: ${{ needs.prepare-dist.outputs.artifact-id }}
    - name: Extract dist
      run: tar -xf ${{ needs.prepare-dist.outputs.dist }}
    - name: Install dependencies
      run: sudo apt update && sudo apt install --no-install-recommends desktop-file-utils gettext libadwaita-1-dev libfuse2 libgtk-4-bin libgtk-4-dev libgtksourceview-5-dev librsvg2-common meson jq
    - name: Build
      run: |
        cd ${{ needs.prepare-dist.outputs.root }}
        meson setup build -Dappimage=enabled -Dprofile=development --prefix=/usr
        ninja -C build
        DESTDIR=$PWD/AppDir ninja -C build install
        curl -LO https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-$(uname -m).AppImage
        chmod a+x appimagetool-$(uname -m).AppImage
        VERSION="${{ needs.prepare-dist.outputs.version }}" ./appimagetool-$(uname -m).AppImage AppDir
    - name: Upload
      uses: actions/upload-artifact@v6
      with:
        name: Cartero-${{ needs.prepare-dist.outputs.version }}-${{ matrix.platform.name }}.AppImage
        path: ${{ needs.prepare-dist.outputs.root }}/Cartero-*.AppImage

  # This one builds the Snapcraft package
  gnulinux-snapcraft:
    needs: [prepare-dist]
    strategy:
      matrix:
        platform:
          - runs-on: ubuntu-latest
            name: x86_64
          - runs-on: ubuntu-24.04-arm
            name: aarch64
      fail-fast: false
    runs-on: ${{ matrix.platform.runs-on }}
    name: "GNU/Linux Snap ${{ matrix.platform.name }}"
    steps:
      - name: Fetch dist
        uses: actions/download-artifact@v7
        with:
          artifact-ids: ${{ needs.prepare-dist.outputs.artifact-id }}
      - name: Extract dist
        run: tar -xf ${{ needs.prepare-dist.outputs.dist }}
      - name: Build Snap
        id: build-snap
        uses: snapcore/action-build@v1
        with:
          path: ${{ needs.prepare-dist.outputs.root }}
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: cartero_${{ needs.prepare-dist.outputs.version }}_${{ matrix.platform.name }}.snap
          path: ${{ steps.build-snap.outputs.snap }}

  # A side action to compile the jhb working dir and cache it.
  macos-jhb:
    needs: [check-new-commits]
    strategy:
      matrix:
        platform:
          - runs-on: macos-15-intel
            name: x64
          - runs-on: macos-26
            name: arm64
      fail-fast: false
    name: "Prepare macOS ${{ matrix.platform.name }} buildenv"
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Fetch jhbuild
        id: cache-jhbuild
        uses: actions/cache/restore@v4
        with:
          path: /Users/Shared/work
          key: jhb-${{ matrix.platform.name }}-49.3
      - name: Compile jhbuild
        if: ${{ steps.cache-jhbuild.outputs.cache-hit != 'true' }}
        run: packaging/macos/jhbuild/main.sh
      - name: Cache jhbuild
        if: ${{ steps.cache-jhbuild.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: /Users/Shared/work
          key: jhb-${{ matrix.platform.name }}-49.3
  # The main compilation pipeline for macOS
  macos-dmg:
    needs: [prepare-dist, macos-jhb]
    strategy:
      matrix:
        platform:
          - runs-on: macos-15-intel
            name: x64
          - runs-on: macos-26
            name: arm64
      fail-fast: false
    name: "macOS DMG ${{ matrix.platform.name }}"
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Fetch dist
        uses: actions/download-artifact@v7
        with:
          artifact-ids: ${{ needs.prepare-dist.outputs.artifact-id }}
      - name: Extract dist
        run: tar -xf ${{ needs.prepare-dist.outputs.dist }}
      - name: Fetch jhbuild
        id: cache-jhbuild
        uses: actions/cache/restore@v4
        with:
          path: /Users/Shared/work
          key: jhb-${{ matrix.platform.name }}-49.3
      - name: Install dependencies
        run: brew install create-dmg
      - name: Fix GETTEXT_DIR for macOS
        run: echo "GETTEXT_DIR=/Users/Shared/work/jhb-1.3+meson184" >> $GITHUB_ENV
      - name: Build macOS version
        run: |
          export PATH=/Users/Shared/work/jhb-1.3+meson184/bin:${PATH}
          cd ${{ needs.prepare-dist.outputs.root }}
          meson setup -Dprofile=development -Dmacos-app=enabled --prefix=/ build
          DESTDIR=$PWD/output ninja -C build install
      - uses: actions/upload-artifact@v4
        name: Upload macOS version
        with:
          name: Cartero-${{ needs.prepare-dist.outputs.version }}-macOS-${{ matrix.platform.name }}
          path: ${{ needs.prepare-dist.outputs.root }}/output/*
