name: Snapcraft Edge
on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  workflow_dispatch:
jobs:
  publish:
    strategy:
      matrix:
        platform:
          - runs-on: ubuntu-latest
            name: x86_64
          - runs-on: ubuntu-24.04-arm
            name: aarch64
      fail-fast: false
    runs-on: ${{ matrix.platform.runs-on }}
    name: "Edge ${{ matrix.platform.name }}"
    steps:
      - uses: actions/checkout@v4
      - uses: snapcore/action-build@v1
        id: build-snap
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_LOGIN }}
        with:
          snap: ${{ steps.build-snap.outputs.snap }}
